<?php
/**
 * Endpoint Manager ARI File
 *
 * @author Andrew Nagy
 * @license MPL / GPLv2 / LGPL
 * @package Endpoint Manager
 */

/**
 * @file
 * Functions for the interface to the call monitor recordings
 */

/**
 * Class for settings
 */
class phonesettings {
    /*
   * rank (for prioritizing modules)
    */
    function rank() {

        $rank = 10;
        return $rank;
    }

    /*
   * init
    */
    function init() {
    }

    /*
   * Adds menu item to nav menu
   *
   * @param $args
   *   Common arguments
    */
    function navMenu($args) {

        $ret = "";
        $exten = $_SESSION['ari_user']['extension'];

        $sql = "SELECT * FROM endpointman_global_vars WHERE var_name = 'enable_ari'";
        $results = $_SESSION['dbh_asterisk']->getAll($sql, DB_FETCHMODE_ASSOC);

        // and we are not logged in as admin
        if (($exten!=$ARI_ADMIN_USERNAME) AND ($results[0]['value'])) {
            $ret .= "<p><small><small><a href='" . $_SESSION['ARI_ROOT'] . "?m=phonesettings&f=display'>" . _("Phone Settings") . "</a></small></small></p><br>";
        }

        return $ret;
    }

    /*
   * Acts on the user settings
   *
   * @param $args
   *   Common arguments
   * @param $a
   *   action
    */
    function action($args) {
        global $endpoint, $global_cfg;

        $doc_root =	$_SERVER["DOCUMENT_ROOT"] ."/admin/modules/endpointman/";
        require($doc_root . "includes/functions.inc");

        $endpoint = new endpointmanager();

        $sql = "SELECT mac_id, line FROM endpointman_line_list WHERE ext = '".$_SESSION['ari_user']['extension']."' ";
        $mac_row =& $endpoint->db->getRow($sql, array(), DB_FETCHMODE_ASSOC);

        $mac_id = $mac_row['mac_id'];
        $line = $mac_row['line'];

        $row = $endpoint->get_phone_info($mac_id);

        $cfg_data = unserialize($row['template_data']);

        $custom_cfg_data2 = unserialize($row['global_custom_cfg_data']);

        if($row['template_id'] > 0) {
            $custom_cfg_data2 = unserialize($row['template_data_info']['global_custom_cfg_data']);
        } else {
            $custom_cfg_data2 = unserialize($row['global_custom_cfg_data']);
        }

        if (!empty($custom_cfg_data2)) {
            if(array_key_exists('data', $custom_cfg_data2)) {
                $custom_cfg_data_data = $custom_cfg_data2['data'];
                $custom_cfg_data_ari = $custom_cfg_data2['ari'];
            } else {
                $custom_cfg_data_data = array();
                $custom_cfg_data_ari = array();
            }
        }

        $custom_cfg_data = array();
        foreach($custom_cfg_data_ari as $key => $data) {
            if(isset($_REQUEST[$key])) {
                $custom_cfg_data[$key] = $_REQUEST[$key];
            }
        }

        $custom_cfg_data = serialize($custom_cfg_data);

        $sql = "UPDATE endpointman_mac_list SET global_user_cfg_data = '".$custom_cfg_data."' WHERE id = ". $mac_id;
        $endpoint->db->query($sql);

        //refresh the data before we prepare so we get acurate data
        $row['global_user_cfg_data'] = $custom_cfg_data;
        $endpoint->prepare_configs($row);

        $m = "phonesettings";

        $ret .= "
      <head>
        <script>
        <!--
          window.location = \"" . $_SESSION['ARI_ROOT'] . "?m=" . $m . "\"
        // -->
        </script>
    </head>";

        return $ret;
    }

    function reloadSettings($exten) {

    }

    /*
   * Displays stats page
   *
   * @param $args
   *   Common arguments
    */
    function display($args) {
        if (!isset($_SESSION['dbh_asterisk'])) {
            die('No Database?');
        }

        $doc_root =	$_SERVER["DOCUMENT_ROOT"] ."/admin/modules/endpointman/";
        require($doc_root . "includes/functions.inc");

        $endpoint = new endpointmanager();

        $sql = "SELECT mac_id, line FROM endpointman_line_list WHERE ext = '".$_SESSION['ari_user']['extension']."' ";

        $res =& $endpoint->db->query($sql);
        if($res->numRows()) {

            $mac_row =& $endpoint->db->getRow($sql, array(), DB_FETCHMODE_ASSOC);

            $mac_id = $mac_row['mac_id'];
            $line = $mac_row['line'];

            $row = $endpoint->get_phone_info($mac_id);

            if(!$endpoint->sync_model($row['model_id'])) {
                die("unable to sync local template files");
            }

            $brand_name = $row['directory'];
            $model_name = $row['cfg_dir'];

            if($row['template_id'] > 0) {
                $ari = unserialize($row['template_data_info']['global_custom_cfg_data']);
            } else {
                $ari = unserialize($row['global_custom_cfg_data']);
            }
            if(!empty($ari['ari'])) {
                //Start the display of the html file in the product folder

                $template =  '<h3>Hello '. $row['line'][$line]['description'] . ', You are currently editing phone settings for extension '.$row['line'][$line]['ext'].'</h3><br />';

                if($row['template_id'] > 0) {
                    $out = $endpoint->generate_gui_html($row['template_data'],$row['template_data_info']['global_custom_cfg_data'],FALSE,$row['global_user_cfg_data'],NULL,$_SESSION['ari_user']['extension']);
                } else {
                    $out = $endpoint->generate_gui_html($row['template_data'],$row['global_custom_cfg_data'],FALSE,$row['global_user_cfg_data'],NULL,$_SESSION['ari_user']['extension']);
                }

                if(!empty($out)) {
                    $out[0]['data'] = array_values($out[0]['data']);
                    $button = "<input name='submit' type='submit' value='Save & Reboot'>";
                } else {
                    $out[0]['title'] = "Your Phone Settings have not been enabled. Please talk to your administrator.";
                    $out[0]['data'] = NULL;
                    $button = "";
                }

                $endpoint->tpl->assign("in_ari", 1);
                $endpoint->tpl->assign("template_editor", $out);
                $endpoint->tpl->assign("hidden_id", $row['line'][$line]['luid']);
                $template .= $endpoint->tpl->draw( 'template_editor', TRUE );


                $m = "phonesettings";
                $ret = "<form class='phonesettings' name='ari_settings' action='' method='GET'>
                        <input type=hidden name=m value=" . $m . ">
                        <input type=hidden name=f value='action'>
                        <input type=hidden name=a value='update'>
                        <br>
                        " . $template . "
                        <br>". $button ."</form>";
                ini_set('display_errors', 0);
                return($ret);
            } else {
                $m = "phonesettings";
                $ret = "<h3>This User/Extension has no settings defined for you to control, Please talk to your administrator</h3>";
                ini_set('display_errors', 0);
                return($ret);
            }
        } else {
            $m = "phonesettings";
            $ret = "<h3>This User/Extension is not managed by Endpoint Manager, Please talk to your administrator</h3>";
            ini_set('display_errors', 0);
            return($ret);
        }
    }
}